### ISSUE TITLE
Add more element icons

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/properties-panel-next#13]
__What should we do?__

Starting with https://github.com/bpmn-io/properties-panel-next/pull/12 we introduce displaying very specific icons depending on the selected element. Currently, the amount of these icons is very limited. We should
* add more, cf. [icons registery](https://github.com/bpmn-io/properties-panel-next/blob/main/src/bpmn-properties-panel/icons/index.js)
* the icons should be displayed in a view box with 32x32 pixels.

We should also consider whether we want to make the current behavior less specific, e.g. not handling markers.

Work happens on [`13-add-more-icons`](https://github.com/bpmn-io/properties-panel-next/tree/13-add-more-icons)

Things to consider: Is there a better way to provide the icons instead of simply importing them [one-by-one](https://github.com/bpmn-io/properties-panel-next/commit/027894f25ea2cea11b156535cb43bccbdcf119e0)?

__Why should we do it?__

Show fewer defaults.

Related to https://github.com/camunda/camunda-modeler-design/issues/13
https://github.com/camunda/camunda-modeler-design/tree/main/icons/bpmn

**Comment by pinussilvestrus** [comment]
@andreasgeier We decided that we don't use the markers in the icons right now. Do we still show them for the type labels?

Background: technically it would be much easier to not handle the markers at all because the mechanism to show label + icon is the same (type => icon + label). 

Additionally, with the markers, the labels will get very long (e.g. Expanded Sub Process (Sequential).

**Comment by andreasgeier** [comment]
> Background: technically it would be much easier to not handle the markers at all (for now)

If it makes the current implementation easier, we can ignore it and find out later if it is helpful as additional information.
