### ISSUE TITLE
Add content marker for (normal) groups

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/properties-panel-next#23]
__Is your feature request related to a problem? Please describe__

With the new properties panel, it should be easier to discover which groups are containing data and which not.

![image](https://user-images.githubusercontent.com/9433996/123072691-0ac53f00-d416-11eb-9438-6b771ed3c517.png)

![image](https://user-images.githubusercontent.com/9433996/123072738-14e73d80-d416-11eb-858f-108f24f56290.png)

As a general rule of thumb, when creating a new element, all groups shall be _not_ marked as dirty (except for the general group, because the id is always filled).

We would like to indicate the dirty state via a visual representation (like we have it for the badge count). The "bold" / "greyed out" state should be gone.

We consider following states as "dirty" (tbd):
* TextField   => value !== empty
* TextArea => value !== empty
* Checkbox => checked != false
* Toggle Switch => checked != false
* Select => value !== empty
* Propagate all child => checked != false

__Describe the solution you'd like__

Mark groups as "empty" when there is nothing configured.

__Describe alternatives you've considered__

/

__Additional context__

With https://github.com/bpmn-io/properties-panel-next/pull/19 we already introduce data markers for lists (count badges).
Zeplin: https://app.zeplin.io/project/5e149dc7ef8eaa51b52af327/dashboard?seid=60d2feb861f9d712892eb17e

**Comment by andreasgeier** [comment]
Find the design issue here: https://github.com/camunda/camunda-modeler-design/issues/22

**Comment by pinussilvestrus** [comment]
**Group title attribute (including data markers, proposal)**

normal group - empty
![image](https://user-images.githubusercontent.com/9433996/123215763-21789e00-d4c9-11eb-852e-246576be2816.png)

normal group - has data
![image](https://user-images.githubusercontent.com/9433996/123215835-335a4100-d4c9-11eb-9f2e-d3d5e85556f3.png)

lists - empty
![image](https://user-images.githubusercontent.com/9433996/123215933-4d941f00-d4c9-11eb-8916-d43e51487d8a.png)

lists - has items
![image](https://user-images.githubusercontent.com/9433996/123216036-68669380-d4c9-11eb-93af-65560eb78855.png)

**Comment by andreasgeier** [comment]
Proposal for titles:

Sections without changes: just the title like `Documentation`
Section with changes: `General (edited)`
Empty Lists: just the title like `Input`
Lists with content: `Output (2 items)`

**Comment by andreasgeier** [comment]
Note: We have to consider the interplay with the split concept. Meaning, as an edge case, a set of properties could be dirty in execution mode, but untouched in design mode (because only an execution property was added). If this is not yet part of the solution, we can postpone until we actually implement the design provider, but should keep it in mind.
