### ISSUE TITLE
In a group entry, the whole entry header should be clickable

### ISSUE THREAD

**Issue by barmac** [bpmn-io/properties-panel-next#47]
UX suggestion: Just like we make the whole entry header clickable when there are some inputs/outputs, I'd expect that clicking on the entry in case of no inputs/outputs will create one. See the screencast:

https://user-images.githubusercontent.com/28307541/120453209-1ed7cc80-c393-11eb-8424-fe02490de113.mp4

_Originally posted by @barmac in https://github.com/bpmn-io/properties-panel-next/issues/37#issuecomment-852855246_

**Comment by andreasgeier** [comment]
I disagree. __A click on equal elements should not trigger different actions.__

The section header allows to expand and to collapse its content. To have a different action on another section is unexpected - even if there is a slightly different state (empty vs not empty). Create (and later other possible actions like full-width, context-menu, etc.) need a dedicated click on the icon.

Please stick to the described behavior.

**Comment by barmac** [comment]
Sure, it's just a suggestion.

**Comment by andreasgeier** [comment]
> Sure, it's just a suggestion.

And that is always welcome! ❤️
