### ISSUE TITLE
Documentation component does not account for `textFormat`

### ISSUE THREAD

**Issue by nikku** [bpmn-io/properties-panel-next#51]
__Describe the Bug__

Documentation should account for `textFormat` properties and only update, never override the entire documentation list for an element. Cf. https://github.com/bpmn-io/bpmn-js-properties-panel/pull/465 where we fixed this in the current properties panel.

__Steps to Reproduce__

* Open an element with more than one documentation element (cf. [example diagram](https://github.com/bpmn-io/bpmn-js-properties-panel/blob/028fd2546b9d71e6616edc89b7a998458ceb98d4/test/spec/provider/bpmn/Documentation.bpmn) `#MULTIPLE_DOCS`)
* See wrong (non `text/plain` text format) entry being displayed
* See whole list being deleted if you update the documention entry

__Expected Behavior__

* [ ] Documentation `textFormat` is accounted for and documentation is updated rather than overriden (https://github.com/bpmn-io/bpmn-js-properties-panel/pull/465).

__Environment__

- Host (Browser/Node version), if applicable: Any
- OS: Any
- Library version: `master`

**Comment by pinussilvestrus** [comment]
That's indeed unexpected since [I thought we cover this one](https://github.com/bpmn-io/properties-panel-next/blob/main/src/bpmn-properties-panel/provider/bpmn/properties/DocumentationProps.js#L97) - probably not.

**Comment by nikku** [comment]
Let me double check then. Maybe I messed something up :D

**Comment by nikku** [comment]
Haha. Not sure which file I looked into, not sure which interaction I just tried...

Works as expected. We also have tests for it. My bad :walking:.

**Comment by pinussilvestrus** [comment]
The more we test those stuff the better we get 👍  Thanks for trying around 🚀
