### ISSUE TITLE
Adding codecov

### ISSUE THREAD

**Issue by pinussilvestrus** [bpmn-io/properties-panel-next#52]
__What should we do?__

Since the codebase and the properties support becomes bigger, we should add code coverage (as codecov) to this library.

__Why should we do it?__

Like we have in other projects, it would increase our confidence we also cover different edge cases.

Cf. how we do it in form-js: https://github.com/bpmn-io/form-js/commit/999afdc81983ff868011cae2d2625603427c74e0

**Comment by nikku** [comment]
Let's not consider, let's do it :).

I [did the same thing for form-js](https://github.com/bpmn-io/form-js/commit/999afdc81983ff868011cae2d2625603427c74e0) just a few days ago. Codecov + decent test story (we have that one) is our baseline.
